name = "gojuon-puzzle-classroom"
main = "worker.js"
compatibility_date = "2026-09-01"
account_id = "f22637eb525d873732e2bbf17772480b"
workers_dev = true

[durable_objects]
bindings = [{ name = "ROOMS", class_name = "ClassroomRoom" }]

[[migrations]]
tag = "v1"
new_sqlite_classes = ["ClassroomRoom"]
